config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  get 'information/show'

  get 'logouts/show'

  get 'profiles/show'

  get 'mypages/show'

  get 'mypages/information', to: 'mypages#information'


  devise_for :users
  resources :signup do
    collection do
      get 'step00'
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' # ここで、入力の全てが終了する
      get 'step5'
    end
  end
  root to: 'home#top'

  resources :items do
    collection do
      get "select", to: "items#select"
      get "select_grand", to: "items#select_grand"
      get "my_item/:id",to: "items#my_item"
    end
  end

  resources :categories, only: [:index]
  resources :purchases, only: [:index, :edit, :update]


  resource :mypages do
    resource :profile ,only: [:show]
    resource :logout ,only: [:show]
    resource :information ,only: [:show]
  end


  resources :credit_cards, only: [:new, :show] do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
      get  'get'  ,  to: 'credit_cards#add_card'
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :user, optional: true

  # validates :address_last_name,               presence: true
  # validates :address_first_name,              {presence: true}
  # validates :address_last_name_kana,          {presence: true}
  # validates :address_first_name_kana,         {presence: true}
  # validates :address_number,          {presence: true}
  # validates :address_prefecture,         {presence: true}
  # validates :address_name,           {presence: true}
  # validates :address_block,          {presence: true}
  # validates :address_building,         {presence: true}
  # validates :address_phone_number,           {presence: true}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  has_many :users
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images
  # belongs_to :user, foreign_key: 'user_id'
  belongs_to :category

  belongs_to :seller ,class_name: "User", foreign_key: "seller_id"
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture


  enum status: { new_thing: 0, near_unused: 1, no_damage: 2, little_damage: 3, damage: 4, bad_thing: 5 }
  enum delivery_cost: { postage_included: 0, cash_on_delivery: 1 }
  enum delivery_way: { undecided: 0, mercari_bin: 1, yu_mail: 2, letter_pack: 3, regular_mail: 4, kuroneko: 5, yu_pack: 6, click_post: 7, yu_packet: 8 }
  enum delivery_date: { ship_in_1to2days: 0, ship_in_2to3days: 1, ship_in_4to7days:2 }
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  belongs_to :item, optional: true
  mount_uploader :image, ImageUploader
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX =                 /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_LAST_NAME =                 /\A[一-龥ぁ-ん]/
  VALID_LAST_NAME_KANA =                 /\A[ァ-ヶー－]+\z/
  VALID_PHONE_NUMBER =                 /\A\d{10,11}\z/
  validates :nickname,                presence: true, length: {maximum: 20}, on: :step2
  validates :email,                   presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }, on: :step2
  validates :password,                presence: true, length: {minimum: 7, maximum: 128}, on: :step2
  validates :password_confirmation,   presence: true, length: {minimum: 7, maximum: 128}, on: :step2
  validates :last_name,               presence: true, format: { with: VALID_LAST_NAME }, on: :step2
  validates :first_name,              presence: true, format: { with: VALID_LAST_NAME }, on: :step2
  validates :last_name_kana,          presence: true, format: { with: VALID_LAST_NAME_KANA },on: :step2
  validates :first_name_kana,         presence: true, format: { with: VALID_LAST_NAME_KANA },on: :step2
  validates :birthdate_year,          presence: true, on: :step2
  validates :birthdate_month,         presence: true, on: :step2
  validates :birthdate_day,           presence: true, on: :step2
  validates :phone_number,            presence: true, on: :step3


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :buyer_transactions, class_name: 'Transaction', :foreign_key => 'buyer_id'
  has_many :seller_transactions, class_name: 'Transaction', :foreign_key => 'seller_id'
  has_many :items
  has_one   :card
  has_one :address
  accepts_nested_attributes_for :address
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  require 'payjp'


  def index
  end

  def edit
    @item = Item.find(params[:id])
    @user = User.find(current_user)
    @address = Address.find(current_user)
    @card = CreditCard.where(user_id: current_user.id).first
    if @card
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
      @exp_month = @default_card_information.exp_month.to_s
      @exp_year = @default_card_information.exp_year.to_s.slice(2,3)
    end
  end

  def update
    @item = Item.find(params[:id])
    
    @card = CreditCard.where(user_id: current_user.id).first
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    Payjp::Charge.create(
    :amount => @item.price,
    :customer => @card.customer_id,
    :currency => 'jpy',
  )

    @item.update(buyer_id: current_user.id)
    redirect_to controller: 'purchases', action: 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/logouts_helper.rb
module LogoutsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/purchases/edit.html.haml
= render "shared/items_header"

.ichi__items__buy
  .ichi__items__buy__one
    購入内容の確認
  .ichi__items__buy__two
    .ichi__items__buy__two__title
      .ichi__items__buy__two__title__image
        =image_tag @item.item_images[0].image, class: "ichi__item__buy__image"
      .ichi__items__buy__two__title__name
        = @item.name
    .ichi__items__buy__two__price
      .ichi__items__buy__two__price__number
        ¥
        = @item.price.to_s(:delimited, delimiter: ',')
      .ichi__items__buy__two__price__text
        送料込み
    .ichi__items__buy__two__point
      ポイントはありません
    .ichi__items__buy__two__payment
      .ichi__items__buy__two__payment__text
        支払い金額
      .ichi__items__buy__two__payment__number
        ¥
        = @item.price.to_s(:delimited, delimiter: ',')
    - if @card.blank?
      .ichi__items__buy__two__confirmation
        配送先と支払い方法の入力お完了してください。
      .ichi__items__buy__two__nobuy
        購入する
    - else
      = link_to purchase_path(@item), method: :patch, data: { confirm: '商品を購入しますか？' }, class: "link__to__buy" do
        .ichi__items__buy__two__buy
          購入する


  .ichi__items__buy__three
    .ichi__items__buy__three__text
      配送先
    .ichi__items__buy__three__address
      .ichi__items__buy__three__address__top
        〒
        = @address.address_number
        <br>
        = @address.address_prefecture
        = @address.address_name
        = @address.address_block
        = @address.address_building
        = @address.address_phone_number
        <br>
        = @user.last_name
        = @user.first_name

    = link_to items_path, class: "ichi_change" do
      .ichi__items__buy__three__change
        .ichi__items__buy__three__change__text
          変更する
        .ichi__items__buy__three__change__icon
          =fa_icon 'chevron-right'
  .ichi__items__buy__four
    .ichi__items__buy__four__text
      支払い方法
    -if @card.present?
      .ichi__items__buy__four__card
        **** **** **** 
        = @default_card_information.last4
        = @exp_month + " / " + @exp_year
    - else
      .ichi__items__buy__four__card
        <br><br><br>
    = link_to new_credit_card_path, class: "ichi_change" do
      .ichi__items__buy__three__change
        .ichi__items__buy__three__change__text
          変更する
        .ichi__items__buy__three__change__icon
          =fa_icon 'chevron-right'

= render "shared/signup-footer"

app/views/purchases/index.html.haml
= render "shared/header"

.ichi__action__complete
  処理が完了しました

= render "shared/footertop"
= render "shared/footer"