config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  get 'information/show'

  get 'logouts/show'

  get 'profiles/show'

  get 'mypages/show'

  get 'mypages/information', to: 'mypages#information'


  devise_for :users
  resources :signup do
    collection do
      get 'step00'
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' # ここで、入力の全てが終了する
      get 'step5'
    end
  end
  root to: 'home#top'

  resources :items do
    collection do
      get "select", to: "items#select"
      get "select_grand", to: "items#select_grand"
      get "my_item/:id",to: "items#my_item"
    end
  end

  resources :categories, only: [:index]
  resources :purchases, only: [:index, :edit, :update]


  resource :mypages do
    resource :profile ,only: [:show]
    resource :logout ,only: [:show]
    resource :information ,only: [:show]
  end


  resources :credit_cards, only: [:new, :show] do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
      get  'get'  ,  to: 'credit_cards#add_card'
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :user, optional: true

  # validates :address_last_name,               presence: true
  # validates :address_first_name,              {presence: true}
  # validates :address_last_name_kana,          {presence: true}
  # validates :address_first_name_kana,         {presence: true}
  # validates :address_number,          {presence: true}
  # validates :address_prefecture,         {presence: true}
  # validates :address_name,           {presence: true}
  # validates :address_block,          {presence: true}
  # validates :address_building,         {presence: true}
  # validates :address_phone_number,           {presence: true}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  has_many :users
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images
  # belongs_to :user, foreign_key: 'user_id'
  belongs_to :category

  belongs_to :seller ,class_name: "User", foreign_key: "seller_id"
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture


  enum status: { new_thing: 0, near_unused: 1, no_damage: 2, little_damage: 3, damage: 4, bad_thing: 5 }
  enum delivery_cost: { postage_included: 0, cash_on_delivery: 1 }
  enum delivery_way: { undecided: 0, mercari_bin: 1, yu_mail: 2, letter_pack: 3, regular_mail: 4, kuroneko: 5, yu_pack: 6, click_post: 7, yu_packet: 8 }
  enum delivery_date: { ship_in_1to2days: 0, ship_in_2to3days: 1, ship_in_4to7days:2 }
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  belongs_to :item, optional: true
  mount_uploader :image, ImageUploader
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX =                 /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_LAST_NAME =                 /\A[一-龥ぁ-ん]/
  VALID_LAST_NAME_KANA =                 /\A[ァ-ヶー－]+\z/
  VALID_PHONE_NUMBER =                 /\A\d{10,11}\z/
  validates :nickname,                presence: true, length: {maximum: 20}, on: :step2
  validates :email,                   presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }, on: :step2
  validates :password,                presence: true, length: {minimum: 7, maximum: 128}, on: :step2
  validates :password_confirmation,   presence: true, length: {minimum: 7, maximum: 128}, on: :step2
  validates :last_name,               presence: true, format: { with: VALID_LAST_NAME }, on: :step2
  validates :first_name,              presence: true, format: { with: VALID_LAST_NAME }, on: :step2
  validates :last_name_kana,          presence: true, format: { with: VALID_LAST_NAME_KANA },on: :step2
  validates :first_name_kana,         presence: true, format: { with: VALID_LAST_NAME_KANA },on: :step2
  validates :birthdate_year,          presence: true, on: :step2
  validates :birthdate_month,         presence: true, on: :step2
  validates :birthdate_day,           presence: true, on: :step2
  validates :phone_number,            presence: true, on: :step3


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :buyer_transactions, class_name: 'Transaction', :foreign_key => 'buyer_id'
  has_many :seller_transactions, class_name: 'Transaction', :foreign_key => 'seller_id'
  has_many :items
  has_one   :card
  has_one :address
  accepts_nested_attributes_for :address
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/logouts_helper.rb
module LogoutsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSample57b
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    -# %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"}
    -# %script{:src => "/js/jquery.validate.js", :type => "text/javascript"}
    -# %script{:src => "/js/jquery.validate.handler.js", :type => "text/javascript"}
    -# %script{:src => "/js/messages_ja.js", :type => "text/javascript"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body

    = yield

app/views/shared/_birthday.html.haml
.haya-field__birthday
  .haya-field__birthday__field
    = f.select :birthdate_year do
      %option{:value => ""} -
      %option{:value => "1900"} 1900
      %option{:value => "1901"} 1901
      %option{:value => "1902"} 1902
      %option{:value => "1903"} 1903
      %option{:value => "1904"} 1904
      %option{:value => "1905"} 1905
      %option{:value => "1906"} 1906
      %option{:value => "1907"} 1907
      %option{:value => "1908"} 1908
      %option{:value => "1909"} 1909
      %option{:value => "1910"} 1910
      %option{:value => "1911"} 1911
      %option{:value => "1912"} 1912
      %option{:value => "1913"} 1913
      %option{:value => "1914"} 1914
      %option{:value => "1915"} 1915
      %option{:value => "1916"} 1916
      %option{:value => "1917"} 1917
      %option{:value => "1918"} 1918
      %option{:value => "1919"} 1919
      %option{:value => "1920"} 1920
      %option{:value => "1921"} 1921
      %option{:value => "1922"} 1922
      %option{:value => "1923"} 1923
      %option{:value => "1924"} 1924
      %option{:value => "1925"} 1925
      %option{:value => "1926"} 1926
      %option{:value => "1927"} 1927
      %option{:value => "1928"} 1928
      %option{:value => "1929"} 1929
      %option{:value => "1930"} 1930
      %option{:value => "1931"} 1931
      %option{:value => "1932"} 1932
      %option{:value => "1933"} 1933
      %option{:value => "1934"} 1934
      %option{:value => "1935"} 1935
      %option{:value => "1936"} 1936
      %option{:value => "1937"} 1937
      %option{:value => "1938"} 1938
      %option{:value => "1939"} 1939
      %option{:value => "1940"} 1940
      %option{:value => "1941"} 1941
      %option{:value => "1942"} 1942
      %option{:value => "1943"} 1943
      %option{:value => "1944"} 1944
      %option{:value => "1945"} 1945
      %option{:value => "1946"} 1946
      %option{:value => "1947"} 1947
      %option{:value => "1948"} 1948
      %option{:value => "1949"} 1949
      %option{:value => "1950"} 1950
      %option{:value => "1951"} 1951
      %option{:value => "1952"} 1952
      %option{:value => "1953"} 1953
      %option{:value => "1954"} 1954
      %option{:value => "1955"} 1955
      %option{:value => "1956"} 1956
      %option{:value => "1957"} 1957
      %option{:value => "1958"} 1958
      %option{:value => "1959"} 1959
      %option{:value => "1960"} 1960
      %option{:value => "1961"} 1961
      %option{:value => "1962"} 1962
      %option{:value => "1963"} 1963
      %option{:value => "1964"} 1964
      %option{:value => "1965"} 1965
      %option{:value => "1966"} 1966
      %option{:value => "1967"} 1967
      %option{:value => "1968"} 1968
      %option{:value => "1969"} 1969
      %option{:value => "1970"} 1970
      %option{:value => "1971"} 1971
      %option{:value => "1972"} 1972
      %option{:value => "1973"} 1973
      %option{:value => "1974"} 1974
      %option{:value => "1975"} 1975
      %option{:value => "1976"} 1976
      %option{:value => "1977"} 1977
      %option{:value => "1978"} 1978
      %option{:value => "1979"} 1979
      %option{:value => "1980"} 1980
      %option{:value => "1981"} 1981
      %option{:value => "1982"} 1982
      %option{:value => "1983"} 1983
      %option{:value => "1984"} 1984
      %option{:value => "1985"} 1985
      %option{:value => "1986"} 1986
      %option{:value => "1987"} 1987
      %option{:value => "1988"} 1988
      %option{:value => "1989"} 1989
      %option{:value => "1990"} 1990
      %option{:value => "1991"} 1991
      %option{:value => "1992"} 1992
      %option{:value => "1993"} 1993
      %option{:value => "1994"} 1994
      %option{:value => "1995"} 1995
      %option{:value => "1996"} 1996
      %option{:value => "1997"} 1997
      %option{:value => "1998"} 1998
      %option{:value => "1999"} 1999
      %option{:value => "2000"} 2000
      %option{:value => "2001"} 2001
      %option{:value => "2002"} 2002
      %option{:value => "2003"} 2003
      %option{:value => "2004"} 2004
      %option{:value => "2005"} 2005
      %option{:value => "2006"} 2006
      %option{:value => "2007"} 2007
      %option{:value => "2008"} 2008
      %option{:value => "2009"} 2009
      %option{:value => "2010"} 2010
      %option{:value => "2011"} 2011
      %option{:value => "2012"} 2012
      %option{:value => "2013"} 2013
      %option{:value => "2014"} 2014
      %option{:value => "2015"} 2015
      %option{:value => "2016"} 2016
      %option{:value => "2017"} 2017
      %option{:value => "2018"} 2018
      %option{:value => "2019"} 2019
      %option{:value => "2020"} 2020
    %spa 年
    = f.select :birthdate_month do
      %option{:value => ""} -
      %option{:value => "1"} 1
      %option{:value => "2"} 2
      %option{:value => "3"} 3
      %option{:value => "4"} 4
      %option{:value => "5"} 5
      %option{:value => "6"} 6
      %option{:value => "7"} 7
      %option{:value => "8"} 8
      %option{:value => "9"} 9
      %option{:value => "10"} 10
      %option{:value => "11"} 11
      %option{:value => "12"} 12
    %spa 月
    = f.select :birthdate_day do
      %option{:value => ""} -
      %option{:value => "1"} 1
      %option{:value => "2"} 2
      %option{:value => "3"} 3
      %option{:value => "4"} 4
      %option{:value => "5"} 5
      %option{:value => "6"} 6
      %option{:value => "7"} 7
      %option{:value => "8"} 8
      %option{:value => "9"} 9
      %option{:value => "10"} 10
      %option{:value => "11"} 11
      %option{:value => "12"} 12
      %option{:value => "13"} 13
      %option{:value => "14"} 14
      %option{:value => "15"} 15
      %option{:value => "16"} 16
      %option{:value => "17"} 17
      %option{:value => "18"} 18
      %option{:value => "19"} 19
      %option{:value => "20"} 20
      %option{:value => "21"} 21
      %option{:value => "22"} 22
      %option{:value => "23"} 23
      %option{:value => "24"} 24
      %option{:value => "25"} 25
      %option{:value => "26"} 26
      %option{:value => "27"} 27
      %option{:value => "28"} 28
      %option{:value => "29"} 29
      %option{:value => "30"} 30
      %option{:value => "31"} 31
    %spa 日

app/views/shared/_footer.html.haml
%footer
  .ichi__footer
    .ichi__footer__top
      .ichi__footer__top__own
        .ichi__footer__top__own__title
          メルカリについて
        .ichi__footer__top__own__contents
          %ul
          %li 会社概要（運営会社）
          %li 採用情報
          %li プレスリリース
          %li 公式ブログ
          %li メルカリロゴ利用ガイドライン
        .ichi__footer__top__own__link
          .ichi__footer__top__own__link__twitter
            =fa_icon 'twitter', class: 'ichi__footer_icon'
          .ichi__footer__top__own__link__facebook
            =fa_icon 'facebook', class: 'ichi__footer_icon'
      .ichi__footer__top__two
        .ichi__footer__top__two__title
          ヘルプ＆ガイド
        .ichi__footer__top__two__contents
          %ul
          %li メルカリガイド
          %li らくらくメルカリ便
          %li ゆうゆうメルカリ便
          %li 大型メルカリ便
          %li 車体取引ガイド
          %li メルカリあんしん・あんぜん宣言！
          %li 偽ブランド品撲滅への取り組み
          %li メルカリボックス
      .ichi__footer__top__three
        .ichi__footer__top__three__title
          プライバシーと利用規約
        .ichi__footer__top__three__contents
          .ichi__footer__top__three__contents__left
            %ul
            %li プライバシーポリシー
            %li メルカリ利用規約
            %li あんしんスマホサポート制度に関する利用特約
            %li コンプライアンスポリシー
          .ichi__footer__top__three__contents__right
            %ul
            %li 個人データの安全管理に係る基本方針
            %li 特定商取引に関する表記
            %li 資金決済法に基づく表示
            %li 法令順守と犯罪抑止のために
      .ichi__footer__top__four
        .ichi__footer__top__four__title
          国
        .ichi__footer__top__four__contents
          %ul
          %li 日本
          %li United States
    .ichi__footer__bottom
      .ichi__footer__bottom__mercari
        =image_tag src="footer-mercari-logo.svg"
      .ichi__footer__bottom__2019
        © 2019 Mercari

app/views/shared/_footertop.html.haml
.ichi__main__four
  .ichi__main__four__box
    .ichi__main__four__box__top
      スマホで簡単フリマアプリ
    .ichi__main__four__box__center
      今すぐ無料ダウンロード！
    .ichi__main__four__box__bottom
      .ichi__main__four__box__bottom__mercari
        =image_tag src="mercari_icon.png", class: "ichi__mecari__image"
      .ichi__main__four__box__bottom__apple
        =image_tag src="app-store-logo.svg", class: "ichi__apple__image"
      .ichi__main__four__box__bottom__google
        =image_tag src="google-logo.svg", class: "ichi__google__image"
  .ichi__main__four__iphon
    =image_tag src="iphone_app_image.png", class: "ichi__iphon__image"

app/views/shared/_header.html.haml
%header
  .ichi__top
    .ichi__top__own
      .ichi__top__own__left
        = link_to image_tag("mercari_logo.svg", class: "ichi__image__mercari"), root_path
      .ichi__top__own__right
        .ichi__top__own__right__input
          %input{type: "text", class: 'ichi__search__item', placeholder:'何かお探しですか？'}
        .ichi__top__own__right__icon
          = fa_icon 'search',class: 'ichi__search__icon'
    .ichi__top__two
      .ichi__top__two__left
        .ichi__top__two__left__category
          .ichi__top__two__left__category__icon
            = fa_icon 'list',class: "ichi__icon__left"
          .ichi__top__two__left__category__text
            カテゴリーから探す

          .ichi__categories
            .ichi__categories__parent
              -@parents.each do |parent|
                = link_to "#{parent.name}", items_path, class: "ichi__category", id: "#{parent.id}"
            .ichi__caetgories__children
            .ichi__caetgories__grandchildren
        
        .ichi__top__two__left__brand
          .ichi__top__two__left__brand__icon
            = fa_icon 'tag',class: "ichi__icon__left"
          .ichi__top__two__left__brand__text
            ブランドから探す
      .ichi__top__two__right
      -if user_signed_in?
        .ichi__top__two__right__nice
          .ichi__top__two__right__nice__icon
            = fa_icon 'heart',class: "ichi__icon__right"
          .ichi__top__two__right__nice__text
            いいね！一覧
        .ichi__top__two__right__news
          .ichi__top__two__right__news__icon
            = fa_icon 'bell',class: "ichi__icon__right"
          .ichi__top__two__right__news__text
            お知らせ
        .ichi__top__two__right__todo
          .ichi__top__two__right__todo__icon
            = fa_icon 'check',class: "ichi__icon__right"
          .ichi__top__two__right__todo__text
            やることリスト
        .ichi__top__two__right__mypage
          .ichi__top__two__right__mypage__icon
            =image_tag src="member_photo.png", class: "ichi__image__mypage"
          = link_to "マイページ", mypages_show_path, class: "ichi__top__two__right__mypage__text"
          .ichi__top__two__right__mypage__profile
            .ichi__top__two__right__mypage__profile__own
              =image_tag src="member_photo.png", class: "ichi__image__mypage__fadeout"
            .ichi__top__two__right__mypage__profile__two
              .ichi__top__two__right__mypage__profile__two__name
                こうたろう
              .ichi__top__two__right__mypage__profile__two__status
                評価：０　出品数：０
              .ichi__top__two__right__mypage__profile__two__price
                .ichi__top__two__right__mypage__profile__two__price__text
                  売上金
                .ichi__top__two__right__mypage__profile__two__price__stock
                  ¥0 ＞
              .ichi__top__two__right__mypage__profile__two__point
                .ichi__top__two__right__mypage__profile__two__point__text
                  ポイント
                .ichi__top__two__right__mypage__profile__two__point__stock
                  P0 ＞
            .ichi__top__two__right__mypage__profile__three
              .ichi__top__two__right__mypage__profile__three__link
                .ichi__top__two__right__mypage__profile__three__link__text
                  いいね！一覧
                .ichi__top__two__right__mypage__profile__three__link__mark
                  ＞
              .ichi__top__two__right__mypage__profile__three__link
                .ichi__top__two__right__mypage__profile__three__link__text
                  出品した商品 - 出品中
                .ichi__top__two__right__mypage__profile__three__link__mark
                  ＞
              .ichi__top__two__right__mypage__profile__three__link
                .ichi__top__two__right__mypage__profile__three__link__text
                  出品した商品 - 取引中
                .ichi__top__two__right__mypage__profile__three__link__mark
                  ＞
              .ichi__top__two__right__mypage__profile__three__link
                .ichi__top__two__right__mypage__profile__three__link__text
                  出品した商品 - 売却済み
                .ichi__top__two__right__mypage__profile__three__link__mark
                  ＞
              .ichi__top__two__right__mypage__profile__three__link
                .ichi__top__two__right__mypage__profile__three__link__text
                  購入した商品 - 取引中
                .ichi__top__two__right__mypage__profile__three__link__mark
                  ＞
              .ichi__top__two__right__mypage__profile__three__link
                .ichi__top__two__right__mypage__profile__three__link__text
                  購入した商品 - 過去の取引
                .ichi__top__two__right__mypage__profile__three__link__mark
                  ＞
      -else
        .ichi__top__two__right__sign
          .ichi__top__two__right__sign__up
            = link_to "新規会員登録", step00_signup_index_path, class: "ichi__signup__link"
          .ichi__top__two__right__sign__login
            = link_to "ログイン", new_user_session_path, class: "ichi__login__link"

app/views/shared/_item_exhibit.html.haml
= link_to '/items/new', data: {"turbolinks" => false} do
  .taka__exhibit
    .taka__exhibit__text
      出品
    .taka__exhibit__camera
      = fa_icon 'camera', class: 'ichi__icon__camera'

app/views/shared/_items_header.html.haml
.ichi__items__header
  =image_tag src="mercari_logo.svg", class: "ichi__items__header__mercari"

app/views/shared/_logouts.html.haml
.kawa-log-out-box
  =link_to "ログアウト", destroy_user_session_path, method: :delete, class: "kawa-log-out-box__button"
-# = render "shared/red-camera"

app/views/shared/_profile_form.html.haml
-# = render "shared/red-camera"
.kawa-profile-edit
  .kawa-profile-edit__title
    プロフィール
  .kawa-profile-edit__top-box
    .kawa-profile-edit__top-box__container
      = image_tag "member_photo_noimage_thumb.png", class:"kawa-profile-edit__top-box__avator"
      %input.kawa-profile-edit__top-box__name{placeholder: "nikuname"}
  .kawa-profile-edit__under-box
    .kawa-profile-edit__under-box__input
      =  text_area :profile, :profile, class: "kawa-profile-edit__under-box__input__form",placeholder: "current_user.profile（空であれば定型文を記述してください）" 
    = link_to "変更する", "" ,{class: "kawa-profile-edit__under-box__submit"}

app/views/shared/_side-bar.html.haml
.side-list
  %nav.mypage-nav
    %ul.mypage-nav__list
      %li.side-bar__link-box
        -# = link_to "", class: "side-links" do
        = link_to mypages_show_path, class: "side-links", :method => 'get' do
          マイページ
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to profiles_show_path, class: "side-links", :method => 'get' do
          お知らせ
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          やることリスト
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          いいね！一覧
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to  new_item_url, class: "side-links", :method => 'get' do
          出品する
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          出品した商品 - 出品中
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          出品した商品 - 取引中
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          出品した商品 - 売却済
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          購入した商品 - 過去の取引
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          ニュース一覧
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          評価一覧
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          マイページ
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          お問い合わせ
          %i.fa.fa-angle-right

    %h3.mypage-nav__head
      メルペイ
    %ul.mypage-nav__list
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          売り上げ・振り込み申請
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          ポイント
          %i.fa.fa-angle-right
        
    %h3.mypage-nav__head
      設定
    %ul.mypage-nav__list
      %li.side-bar__link-box
        = link_to mypages_profile_url, class: "side-links", :method => 'get' do
          プロフィール
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          発送元・お届け先住所変更
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to get_credit_cards_url, class: "side-links", :method => 'get' do
          お支払情報変更
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          メール/パスワード
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to  mypages_information_url, class: "side-links", :method => 'get' do
          本人確認
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to "", class: "side-links" do
          電話番号の確認
          %i.fa.fa-angle-right
      %li.side-bar__link-box
        = link_to  logouts_show_url, class: "side-links", :method => 'get' do
          ログアウト
          %i.fa.fa-angle-right

app/views/shared/_signup-footer.html.haml
.haya-footer
  %nav.haya-pura
    プライバシーポリシー　　メルカリ利用メルカリ規約　　特定商取引に関する表記
  %a.haya-meru
    -# = link_to image_tag("sub-footer-logo.svg", width:"80", height:"60"),"#"
    =image_tag src="sub-footer-logo.svg"
  %p.haya-2019
    © 2019 Mercari