config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  get 'information/show'

  get 'logouts/show'

  get 'profiles/show'

  get 'mypages/show'

  get 'mypages/information', to: 'mypages#information'


  devise_for :users
  resources :signup do
    collection do
      get 'step00'
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' # ここで、入力の全てが終了する
      get 'step5'
    end
  end
  root to: 'home#top'

  resources :items do
    collection do
      get "select", to: "items#select"
      get "select_grand", to: "items#select_grand"
      get "my_item/:id",to: "items#my_item"
    end
  end

  resources :categories, only: [:index]
  resources :purchases, only: [:index, :edit, :update]


  resource :mypages do
    resource :profile ,only: [:show]
    resource :logout ,only: [:show]
    resource :information ,only: [:show]
  end


  resources :credit_cards, only: [:new, :show] do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
      get  'get'  ,  to: 'credit_cards#add_card'
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images
  # belongs_to :user, foreign_key: 'user_id'
  belongs_to :category

  belongs_to :seller ,class_name: "User", foreign_key: "seller_id"
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture


  enum status: { new_thing: 0, near_unused: 1, no_damage: 2, little_damage: 3, damage: 4, bad_thing: 5 }
  enum delivery_cost: { postage_included: 0, cash_on_delivery: 1 }
  enum delivery_way: { undecided: 0, mercari_bin: 1, yu_mail: 2, letter_pack: 3, regular_mail: 4, kuroneko: 5, yu_pack: 6, click_post: 7, yu_packet: 8 }
  enum delivery_date: { ship_in_1to2days: 0, ship_in_2to3days: 1, ship_in_4to7days:2 }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :my_item, :buy_confirm]
  before_action :authenticate_user!, only: [:new, :show]

  def index
    # @items = Item.all.order(id: "DESC").limit(10)
    @womenitems = Item.where(category_id: 20..85).order(id: "DESC").limit(10)
    @menitems = Item.where(category_id: 91..144).order(id: "DESC").limit(10)
    @electricalitems = Item.where(category_id: 408..435).order(id: "DESC").limit(10)
    @toyitems = Item.where(category_id: 306..371).order(id: "DESC").limit(10)
    @chanelitems = Item.where(brand: "シャネル").order(id: "DESC").limit(10)
    @louisvuittonitems = Item.where(brand: "ルイヴィトン").order(id: "DESC").limit(10)
    @supremeitems = Item.where(brand: "シュプリーム").order(id: "DESC").limit(10)
    @nikeitems = Item.where(brand: "ナイキ").order(id: "DESC").limit(10)
  end

  def new
    # if user_signed_in?
      # @item = Item.new
      # 5.times{@item.images.build}
    # else
    #   redirect_to new_user_session_path
    # end
    @item = Item.new
    @parents = Category.where(ancestry: nil) #Category.where(ancestry = ?, "nil")
    @item.item_images.build
    
  end

  def create
    @item = Item.new(item_params)
    @parents = Category.where(ancestry: nil)
    @item.save
    if @item.save && new_image_params[:images][0] != ""
      new_image_params[:images].each do |image|
        @item.item_images.create(image: image, item_id: @item.id)
      end
      redirect_to root_path
    else
      @item.item_images.buildparam
      render :new
    end
  end

  def show
    @selleritems = Item.where(seller_id: @item.seller_id).order(id: "DESC").limit(6)
    @branditems = Item.where(brand: @item.brand).order(id: "DESC").limit(6)
    @user = User.find(@item.seller_id)
    @images = ItemImage.where(item_id: @item.id)
  end

  def edit
    @grands = @item.category.root
    @grands_sib = @grands.siblings

    @parents1 = @item.category.parent
    @parents_sib =@parents1.siblings

    @category = @item.category
    @category_sib = @item.category.siblings

    @parents = Category.where(ancestry: nil) #Category.where(ancestry = ?, "nil")
    @item.item_images.build
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      redirect_to action: 'edit'
    end
  end

  def destroy
    @item.destroy
    redirect_to controller: 'purchases', action: 'index'
  end

  def select
    respond_to do |format|
      format.html
      format.json do
        if params[:parent_id]
          @children = Category.find(params[:parent_id]).children
        else
          @grand_children = Category.find(params[:child_id]).children
        end
      end
    end
  end

  def select_grand
    respond_to do |format|
      format.html
      format.json { @grand_children_info = Category.find(params[:grand_id]) }
    end
  end

  def set_item
    @item = Item.find(params[:id])
  end


  private

  def item_params
    params.require(:item).permit(:name, :description, :category_id, :status, :delivery_cost, :delivery_way, :prefecture_id, :delivery_date, :price).merge(seller_id: current_user.id)
  end

  def new_image_params
    params.require(:new_images).permit({images: []})
  end

  private 
  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.haml
.kawa-sell-body
  .kawa-sell-page-container
    .kawa-sell-header
      = render "shared/items_header"
      -# %h1.kawa-sell-header__box
      -#   = link_to root_path, class:"kawa-sell-header__box__link" do
      -#     = image_tag "logo.svg", class:"kawa-sell-header__box__link__image", alt:"mercari"
    .kawa-sell-main
      .kawa-item-container
        .kawa-sell-container
          .kawa-sell-inner
            %h2.kawa-sell-inner__description
              商品の情報を入力
            = form_for @item do |f|
              .kawa-sell-form__upload-box
                %h3.kawa-sell-form__upload-box__head
                  出品画像
                  %span.kawa-sell-form__upload-box__head__require
                    必須
                %p.kawa-sell-form__upload-box__explain
                  最大5枚までアップロードできます
                  .kawa-sell-form__upload-box__dropbox__container__frame
                    %pre.ichi__edit__item__pre
                      -@item.item_images.each do |image|
                        .ichi__edit__item__images
                          =image_tag image.image, class: "ichi__edit__item__image"
                          .kawa-btn_delete
                            削除

                  .ichi__space
              .kawa-sell-form__content
                .kawa-sell-form__content__group--first
                  .kawa-sell-form__content__group__name
                    商品名
                    %span.kawa-sell-form__content__group__name__require
                      必須
                  = f.text_field :name, class: "kawa-sell-form__content__group__input", placeholder: "商品名（必須 40文字まで）"
                .kawa-sell-form__content__group
                  .kawa-sell-form__content__group__name
                    商品の説明
                    %span.kawa-sell-form__content__group__name__require
                      必須
                  = f.text_area :description, class: "kawa-sell-form__content__group__text", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
              .kawa-sell-form__content--non-first
                %h3.kawa-sell-form__content__head
                  商品の詳細
                .kawa-sell-form__content__box
                  .kawa-sell-form__content__box__group--first#kawa-categories
                    .kawa-sell-form__content__box__group__name
                      カテゴリー
                      %span.kawa-sell-form__content__box__group__name__require
                        必須
                    .kawa-sell-form__content__box__group__select
                      = fa_icon 'chevron-down', class:"kawa-arrow-bottom"
                      = f.collection_select :category_id, @grands_sib, :id, :name, {prompt: "---", selected: @grands.id}, class: "kawa-sell-form__content__box__group__select__wrap", id: "kawa-parent-form", name: "item[category_id]"
                      = f.hidden_field :category_id, id:"kawa-cate_id", value:""
                    .kawa-sell-form__content__box__group__select#child-container
                      = fa_icon 'chevron-down', class:"kawa-arrow-bottom"
                      = f.collection_select :category_id, @parents_sib, :id, :name, {prompt: "---", selected: @parents1.id}, class: "kawa-sell-form__content__box__group__select__wrap", id: "kawa-parent-form", name: "item[category_id]"
                      -# = f.hidden_field :category_id, id:"kawa-cate_id", value:""
                    .kawa-sell-form__content__box__group__select#grandchild-container
                      = fa_icon 'chevron-down', class:"kawa-arrow-bottom"
                      = f.collection_select :category_id, @category_sib, :id, :name, {prompt: "---", selected: @category.id}, class: "kawa-sell-form__content__box__group__select__wrap", id: "kawa-parent-form", name: "item[category_id]"
                      -# = f.hidden_field :category_id, id:"kawa-cate_id", value:""
                  .kawa-sell-form__content__box__group
                    .kawa-sell-form__content__box__group__name
                      商品の状態
                      %span.kawa-sell-form__content__box__group__name__require
                        必須
                    .kawa-sell-form__content__box__group__select
                      = fa_icon 'chevron-down', class:"kawa-arrow-bottom"
                      = f.select :status, Item.statuses_i18n.keys.map { |k| [Item.statuses_i18n[k], k]} , {prompt: "---"} ,class: "kawa-sell-form__content__box__group__select__wrap"
              .kawa-sell-form__content--non-first
                %h3.kawa-sell-form__content__head
                  配送について
                = link_to "", class:"kawa-sell-form__content__question" do
                  ?
                .kawa-sell-form__content__box
                  .kawa-sell-form__content__box__group--first
                    .kawa-sell-form__content__box__group__name
                      配送料の負担
                      %span.kawa-sell-form__content__box__group__name__require
                        必須
                    .kawa-sell-form__content__box__group__select
                      = fa_icon 'chevron-down', class:"kawa-arrow-bottom"
                      = f.select :delivery_cost, Item.delivery_costs_i18n.keys.map { |k| [Item.delivery_costs_i18n[k], k]}, {prompt: "---"}, class: "kawa-sell-form__content__box__group__select__wrap"
                  .kawa-sell-form__content__box__group
                    .kawa-sell-form__content__box__group__name
                      配送の方法
                      %span.kawa-sell-form__content__box__group__name__require
                        必須
                    .kawa-sell-form__content__box__group__select
                      = fa_icon 'chevron-down', class:"kawa-arrow-bottom"
                      = f.select :delivery_way, Item.delivery_ways_i18n.keys.map { |k| [Item.delivery_ways_i18n[k], k]}, {prompt: "---"}, class:"kawa-sell-form__content__box__group__select__wrap"
                  .kawa-sell-form__content__box__group
                    .kawa-sell-form__content__box__group__name
                      発送元の地域
                      %span.kawa-sell-form__content__box__group__name__require
                        必須
                    .kawa-sell-form__content__box__group__select
                      = fa_icon 'chevron-down', class:"kawa-arrow-bottom"
                      = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "---"}, class:"kawa-sell-form__content__box__group__select__wrap"
                  .kawa-sell-form__content__box__group
                    .kawa-sell-form__content__box__group__name
                      発送までの日数
                      %span.kawa-sell-form__content__box__group__name__require
                        必須
                    .kawa-sell-form__content__box__group__select
                      = fa_icon 'chevron-down', class:"kawa-arrow-bottom"
                      = f.select :delivery_date, Item.delivery_dates_i18n.keys.map { |k| [Item.delivery_dates_i18n[k], k]}, {prompt: "---"}, class: "kawa-sell-form__content__box__group__select__wrap"
              .kawa-sell-form__content--non-first
                %h3.kawa-sell-form__content__head
                  販売価格(300~9,999,999)
                = link_to "", class:"kawa-sell-form__content__question" do
                  ?
                .kawa-sell-form__content__box
                  %ul.kawa-sell-form__content__box__price
                    %li.kawa-sell-form__content__box__price__group
                      .kawa-sell-form__content__box__price__group__clearfix
                        .kawa-sell-form__content__box__price__group__clearfix__name
                          価格
                          %span.kawa-sell-form__content__box__price__group__clearfix__name__require
                            必須
                        .kawa-sell-form__content__box__price__group__clearfix__input-box
                          .kawa-sell-form__content__box__price__group__clearfix__input-box__yen
                            ¥
                          = f.text_field :price, id: "price_form", class: "kawa-sell-form__content__box__price__group__clearfix__input-box__frame", placeholder: "例）300"
                    %li.kawa-sell-form__content__box__price__clearfix
                      .kawa-sell-form__content__box__price__clearfix__name
                        販売手数料（10%）
                      .kawa-sell-form__content__box__price__clearfix__fee -
                    %li.kawa-sell-form__content__box__price__bold
                      .kawa-sell-form__content__box__price__bold__name
                        販売利益
                      .kawa-sell-form__content__box__price__bold__benefit -
              .kawa-sell-form__content--non-first
                .kawa-sell-form__content__container
                .kawa-sell-form__content__button
                = f.submit "変更する", class:'kawa-sell-form__content__button'
                = link_to "",class:"kawa-sell-form__content__back-button" do
                  もどる
      = render "shared/signup-footer"

app/views/items/index.html.haml
= render "shared/header"

.ichi__main
  .ichi__main__own
    
  .ichi__main__two
    .ichi__main__two__category
      人気のカテゴリー
    .ichi__main__two__categorys
      .ichi__main__two__categorys__list
        レディース
      .ichi__main__two__categorys__list
        メンズ
      .ichi__main__two__categorys__list
        家電・スマホ・カメラ
      .ichi__main__two__categorys__list
        おもちゃ・ホビー・グッズ

  .ichi__main__three

    .ichi__main__three__box
      .ichi__main__three__box__top
        .ichi__main__three__box__top__title
          レディース新着アイテム
        .ichi__main__three__box__top__more
          もっと見る　＞
      .ichi__main__three__box__items
        -@womenitems.each do |item|
          .ichi__main__three__box__items__item
            = link_to item_path(item) do
              -if item.buyer_id.present?
                .ichi__main__three__box__items__item__sold
                .ichi__main__three__box__items__item__soldtext
                  SOLD
              .ichi__main__three__box__items__item__image
              = image_tag item.item_images[0].image, class: "ichi__item__image"
              .ichi__main__three__box__items__item__price
                ¥
                = item.price.to_s(:delimited, delimiter: ',')
                .ichi__main__three__box__items__item__text
                  = item.name

    .ichi__main__three__box
      .ichi__main__three__box__top
        .ichi__main__three__box__top__title
          メンズ新着アイテム
        .ichi__main__three__box__top__more
          もっと見る　＞
      .ichi__main__three__box__items
        -@menitems.each do |item|
          .ichi__main__three__box__items__item
            = link_to item_path(item) do
              .ichi__main__three__box__items__item__image
              = image_tag item.item_images[0].image, class: "ichi__item__image"
              .ichi__main__three__box__items__item__price
                ¥
                = item.price.to_s(:delimited, delimiter: ',')
                .ichi__main__three__box__items__item__text
                  = item.name
      
    .ichi__main__three__box
      .ichi__main__three__box__top
        .ichi__main__three__box__top__title
          家電・スマホ・カメラ新着アイテム
        .ichi__main__three__box__top__more
          もっと見る　＞
      .ichi__main__three__box__items
        -@electricalitems.each do |item|
          = link_to item_path(item) do
            .ichi__main__three__box__items__item
              .ichi__main__three__box__items__item__image
              = image_tag item.item_images[0].image, class: "ichi__item__image"
              .ichi__main__three__box__items__item__price
                ¥
                = item.price.to_s(:delimited, delimiter: ',')
                .ichi__main__three__box__items__item__text
                  = item.name

    .ichi__main__three__box
      .ichi__main__three__box__top
        .ichi__main__three__box__top__title
          おもちゃ・ホビー・グッズ新着アイテム
        .ichi__main__three__box__top__more
          もっと見る　＞
      .ichi__main__three__box__items
        -@toyitems.each do |item|
          = link_to item_path(item) do
            .ichi__main__three__box__items__item
              .ichi__main__three__box__items__item__image
              = image_tag item.item_images[0].image, class: "ichi__item__image"
              .ichi__main__three__box__items__item__price
                ¥
                = item.price.to_s(:delimited, delimiter: ',')
                .ichi__main__three__box__items__item__text
                  = item.name

  .ichi__main__two
    .ichi__main__two__category
      人気のブランド
    .ichi__main__two__categorys
      .ichi__main__two__categorys__list
        シャネル
      .ichi__main__two__categorys__list
        ルイヴィトン
      .ichi__main__two__categorys__list
        シュプリーム
      .ichi__main__two__categorys__list
        ナイキ
  .ichi__main__three
    .ichi__main__three__box
      .ichi__main__three__box__top
        .ichi__main__three__box__top__title
          シャネル新着アイテム
        .ichi__main__three__box__top__more
          もっと見る　＞
      .ichi__main__three__box__items
        -@chanelitems.each do |item|
          = link_to item_path(item) do
            .ichi__main__three__box__items__item
              .ichi__main__three__box__items__item__image
              = image_tag item.item_images[0].image, class: "ichi__item__image"
              .ichi__main__three__box__items__item__price
                ¥
                = item.price.to_s(:delimited, delimiter: ',')
                .ichi__main__three__box__items__item__text
                  = item.name
      
    .ichi__main__three__box
      .ichi__main__three__box__top
        .ichi__main__three__box__top__title
          ルイヴィトン新着アイテム
        .ichi__main__three__box__top__more
          もっと見る　＞
      .ichi__main__three__box__items
        -@louisvuittonitems.each do |item|
          = link_to item_path(item) do
            .ichi__main__three__box__items__item
              .ichi__main__three__box__items__item__image
              = image_tag item.item_images[0].image, class: "ichi__item__image"
              .ichi__main__three__box__items__item__price
                ¥
                = item.price.to_s(:delimited, delimiter: ',')
                .ichi__main__three__box__items__item__text
                  = item.name

    .ichi__main__three__box
      .ichi__main__three__box__top
        .ichi__main__three__box__top__title
          シュプリーム新着アイテム
        .ichi__main__three__box__top__more
          もっと見る　＞
      .ichi__main__three__box__items
        -@supremeitems.each do |item|
          = link_to item_path(item) do
            .ichi__main__three__box__items__item
              .ichi__main__three__box__items__item__image
              = image_tag item.item_images[0].image, class: "ichi__item__image"
              .ichi__main__three__box__items__item__price
                ¥
                = item.price.to_s(:delimited, delimiter: ',')
                .ichi__main__three__box__items__item__text
                  = item.name

    .ichi__main__three__box
      .ichi__main__three__box__top
        .ichi__main__three__box__top__title
          ナイキ新着アイテム
        .ichi__main__three__box__top__more
          もっと見る　＞
      .ichi__main__three__box__items
        -@nikeitems.each do |item|
          = link_to item_path(item) do
            .ichi__main__three__box__items__item
              .ichi__main__three__box__items__item__image
              = image_tag item.item_images[0].image, class: "ichi__item__image"
              .ichi__main__three__box__items__item__price
                ¥
                = item.price.to_s(:delimited, delimiter: ',')
                .ichi__main__three__box__items__item__text
                  = item.name

= render "shared/footertop"
= render "shared/footer"
= render "shared/item_exhibit"

app/views/items/show.html.haml
= render "shared/header"

.ichi__exhibit
  .ichi__exhibit__own
    .ichi__exhibit__own__title
      = @item.name
    .ichi__exhibit__own__item
      .ichi__exhibit__own__item__images
        .ichi__exhibit__own__item__images__top
          = image_tag @item.item_images[0].image, class: "ichi__exhibit__show__top__image", id: @item.id
        .ichi__exhibit__own__item__images__others
          -@images.each_with_index do |image, i|
            .ichi__exhibit__own__item__images__others__image
              = image_tag image.image, id: i, class: "ichi__exhibit__show__images"

      .ichi__exhibit__own__item__description
        .ichi__exhibit__own__item__description__text
          .ichi__exhibit__own__item__description__text__left
            出品者
          .ichi__exhibit__own__item__description__text__right
            .ichi__exhibit__own__item__description__text__right__name
              = link_to items_path, class: "link_to" do
                = @user.nickname
            .ichi__exhibit__own__item__description__text__right__evaluation
              .ichi__exhibit__own__item__description__text__right__evaluation__icon
                = fa_icon 'thumbs-up', class: "ichi__evaluation__icon__red"
              .ichi__exhibit__own__item__description__text__right__evaluation__point
                100 
              .ichi__exhibit__own__item__description__text__right__evaluation__icon
                = fa_icon 'thumbs-down', class: "ichi__evaluation__icon__blue"
              .ichi__exhibit__own__item__description__text__right__evaluation__point
                0
        .ichi__exhibit__own__item__description__text
          .ichi__exhibit__own__item__description__text__left
            カテゴリー
          .ichi__exhibit__own__item__description__text__right
            .ichi__exhibit__own__item__description__text__right__category
              = link_to items_path, class: "link_to" do
                = @item.category.root.name
            .ichi__exhibit__own__item__description__text__right__category
              = link_to items_path, class: "link_to" do
                >
                = @item.category.parent.name
            .ichi__exhibit__own__item__description__text__right__category
              = link_to items_path, class: "link_to" do
                >
                = @item.category.name
        .ichi__exhibit__own__item__description__text
          .ichi__exhibit__own__item__description__text__left
            ブランド
          .ichi__exhibit__own__item__description__text__right
            = link_to items_path, class: "link_to" do
              = @item.brand
        .ichi__exhibit__own__item__description__text
          .ichi__exhibit__own__item__description__text__left
            商品のサイズ
          .ichi__exhibit__own__item__description__text__right
            = @item.size
        .ichi__exhibit__own__item__description__text
          .ichi__exhibit__own__item__description__text__left
            商品の状態
          .ichi__exhibit__own__item__description__text__right
            = @item.status_i18n
        .ichi__exhibit__own__item__description__text
          .ichi__exhibit__own__item__description__text__left
            配送料の負担
          .ichi__exhibit__own__item__description__text__right
            = @item.delivery_cost_i18n
        .ichi__exhibit__own__item__description__text
          .ichi__exhibit__own__item__description__text__left
            配送の方法
          .ichi__exhibit__own__item__description__text__right
            = @item.delivery_way_i18n
        .ichi__exhibit__own__item__description__text
          .ichi__exhibit__own__item__description__text__left
            配送元地域
          .ichi__exhibit__own__item__description__text__right
            = link_to items_path, class: "link_to" do
              = @item.prefecture.name
        .ichi__exhibit__own__item__description__text
          .ichi__exhibit__own__item__description__text__left
            発送日の目安
          .ichi__exhibit__own__item__description__text__right
            = @item.delivery_date_i18n
    .ichi__exhibit__own__price
      .ichi__exhibit__own__price__left
        ¥
        = @item.price.to_s(:delimited, delimiter: ',')
      .ichi__exhibit__own__price__center
        （税込）
      .ichi__exhibit__own__price__right
        送料込み
    -if @user == current_user
      .ichi__exhibit__own__text
        = @item.description
      = link_to edit_item_path(@item), class: "link_to_buy" do
        .ichi__exhibit__own__purchase
          商品の編集
      .ichi__exhibit__own__or
        or
      = link_to item_path(@item), method: :delete, data: { confirm: '商品の出品を取り消してもよろしいですか？' }, class: "link_to_buy" do
        .ichi__exhibit__own__sold
          この商品を削除する
    - else
      -if @item.buyer_id.nil?
        = link_to edit_purchase_path(@item), class: "link_to_buy" do
          .ichi__exhibit__own__purchase
            購入画面に進む
      - else
        .ichi__exhibit__own__sold
          売り切れました
        .ichi__exhibit__own__text
          = @item.description
        .ichi__exhibit__own__contents
          .ichi__exhibit__own__contents__left
            .ichi__exhibit__own__contents__left__evaluation
              .ichi__exhibit__own__contents__left__evaluation__icon
                =fa_icon 'heart'
              .ichi__exhibit__own__contents__left__evaluation__good
                いいね!
              .ichi__exhibit__own__contents__left__evaluation__point
                150
            .ichi__exhibit__own__contents__left__report
              .ichi__exhibit__own__contents__left__report__icon
                =fa_icon 'flag'
              .ichi__exhibit__own__contents__left__report__text
                不適切な商品の報告
          .ichi__exhibit__own__contents__right
            .ichi__exhibit__own__contents__right__icon
              =fa_icon 'lock'
            .ichi__exhibit__own__contents__right__text
              あんしん・あんぜんへの取り組み

  .ichi__exhibit__two
    .ichi__exhibit__two__text
      相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
    .ichi__exhibit__two__input
      %textarea{type: "text", name: "message", class: "ichi__exhibit__message"}
    .ichi__exhibit__two__submit
      %button{type: "submit", class: "ichi__exhibit__submit"}
        コメントする
  .ichi__exhibit__three
    .ichi__exhibit__three__left
      .ichi__exhibit__three__left__icon
        =fa_icon 'chevron-left'
      .ichi__exhibit__three__left__item
        テストアイテム①
    .ichi__exhibit__three__right
      .ichi__exhibit__three__right__item
        テストアイテム②
      .ichi__exhibit__three__right__icon
        =fa_icon 'chevron-right'
  .ichi__exhibit__four
    .ichi__exhibit__four__icon
      =fa_icon 'facebook-square',class: "ichi__exhibit__icon__facebook"
    .ichi__exhibit__four__icon
      =fa_icon 'twitter-square',class: "ichi__exhibit__four__icon__twitter"
    .ichi__exhibit__four__icon
      =fa_icon 'pinterest-square',class: "ichi__exhibit__four__icon__pinterest"
  .ichi__exhibit__five
    .ichi__exhibit__five__name
      = link_to items_path, class: "link_to" do
        = @user.nickname
        さんのその他の出品
    .ichi__exhibit__five__items
    -@selleritems.each do |item|
      = link_to item_path(item), class: "link__to__show" do
        .ichi__exhibit__five__items__item
          .ichi__exhibit__five__items__item__image
            =image_tag item.item_images[0].image, class: "ichi__exhibit__five__image"
          .ichi__exhibit__five__items__item__text
            .ichi__exhibit__five__items__item__text__top
              = item.name
            .ichi__exhibit__five__items__item__text__bottom
              .ichi__exhibit__five__items__item__text__bottom__left
                = item.price.to_s(:delimited, delimiter: ',')
              .ichi__exhibit__five__items__item__text__bottom__right
                .ichi__exhibit__five__items__item__text__bottom__right__icon
                  =fa_icon 'heart'
                .ichi__exhibit__five__items__item__text__bottom__right__point
                  100
      
  
  .ichi__exhibit__five
    .ichi__exhibit__five__name
      = link_to items_path, class: "link_to" do
        = @item.brand
        のその他の商品
    .ichi__exhibit__five__items
    -@branditems.each do |item|
      = link_to item_path(item), class: "link__to__show" do
        .ichi__exhibit__five__items__item
          .ichi__exhibit__five__items__item__image
            =image_tag item.item_images[0].image, class: "ichi__exhibit__five__image"
          .ichi__exhibit__five__items__item__text
            .ichi__exhibit__five__items__item__text__top
              = item.name
            .ichi__exhibit__five__items__item__text__bottom
              .ichi__exhibit__five__items__item__text__bottom__left
                = item.price.to_s(:delimited, delimiter: ',')
              .ichi__exhibit__five__items__item__text__bottom__right
                .ichi__exhibit__five__items__item__text__bottom__right__icon
                  =fa_icon 'heart'
                .ichi__exhibit__five__items__item__text__bottom__right__point
                  100
        
  
  .ichi__exhibit__six
    .ichi__exhibit__six__box
      .ichi__exhibit__six__box__mercari
        メルカリ
      .ichi__exhibit__six__box__icon
        =fa_icon 'chevron-right', class: "ichi__exhibit__six__icon"
      .ichi__exhibit__six__box__item
        テストテスト

=render "shared/footertop"
=render "shared/footer"